name: openvla
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.9.19
  - cuda-runtime=12.4.1
  - cuda-version=12.9
  - dav1d=1.2.1
  - expat=2.7.1
  - ffmpeg=4.3
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libavif=1.1.1
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.9.82
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.7.3
  - networkx=3.4.2
  - numpy-base=2.0.1
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.40.0
  - pthread-stubs=0.3
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.10.18
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.4
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tbb=2021.8.0
  - tk=8.6.14
  - torchtriton=3.1.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.10.0
      - blinker==1.9.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - einops==0.8.1
      - filelock==3.18.0
      - flask==3.1.1
      - fsspec==2025.7.0
      - hf-xet==1.1.7
      - huggingface-hub==0.34.3
      - idna==3.10
      - itsdangerous==2.2.0
      - ninja==1.13.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cufile-cu12==1.14.1.1
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.3.9
      - nvidia-nvtx-cu12==12.9.79
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - psutil==7.0.0
      - pytorch-triton==3.4.0+gitf7888497
      - regex==2025.7.34
      - safetensors==0.6.1
      - sympy==1.14.0
      - timm==0.9.10
      - tokenizers==0.19.1
      - torch==2.9.0.dev20250814+cu129
      - torchvision==0.24.0.dev20250814+cu129
      - tqdm==4.67.1
      - transformers==4.40.1
      - triton==3.3.1
      - typing-extensions==4.14.1
      - werkzeug==3.1.3
